### ISSUE TITLE
讨论区 General Discuession

### ISSUE THREAD

**Issue by shenlebantongying** [rimebrew/rimebrew_cli#2]
Talk anything :smile:

**Comment by sgalal** [comment]
Great! Are you going to create a chat group in a instant messaging software, so that you can post your thoughts there?

**Comment by shenlebantongying** [comment]
@sgalal  大部分东西都讨论过了，这是几个主要的链接：

https://github.com/rime/plum/issues/1
https://github.com/rime/plum/issues/4
https://github.com/rime/plum/issues/23
https://github.com/rime/home/issues/336

目前就是的情况就是 [就差一个程序员](https://www.zhihu.com/question/22989105)，更多的讨论没有什么必要。而且我时间有限，只能先做我觉得重要的东西。而且，当前还不可用，估计还需要一些时间把 /plum/ 有的功能都实现了再说。

**Comment by sgalal** [comment]
What is the current state now?

**Comment by shenlebantongying** [comment]
I am rewriting it with Qt with a nice good-looking GUI.

Command line interface is dumb. Only nerds use a black terminal.

I am having some final exams right now, so it is paused recently.
